name: Python package
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
      - name: Increment patch version
        run: poetry version patch
      - name: Commit and push changes
        run: |
          git config --local user.email "
          git config --local user.name "
          git add pyproject.toml
          git commit -m "Bump patch version"
          git push
